<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_Flow_Demo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0eea4fdb-173f-4f84-b50f-14e3ba164e30</testSuiteGuid>
   <testCaseLink>
      <guid>30e27302-c513-438e-bf7a-fe1f05093bf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/TC01_Login_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e4db6fc7-7a6a-4f21-8dc4-1764b1067c2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Module/TC01_NewCustomer</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>738db0af-b1cf-4eef-bb61-6f4895467a1a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CustomerID_List</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>caf30f8d-6646-4245-a6c3-67008021c62a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Customer_Input</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5d6c14ea-62ca-4890-a3ae-f15f72409ac4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AccountID_List</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>caf30f8d-6646-4245-a6c3-67008021c62a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>v_Name</value>
         <variableId>acfa4121-b000-4226-9fd8-88cbea58b967</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>caf30f8d-6646-4245-a6c3-67008021c62a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>v_Dob</value>
         <variableId>5b29783c-9ed3-4945-875f-5064a6e48917</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>caf30f8d-6646-4245-a6c3-67008021c62a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>v_Addr</value>
         <variableId>5401ea89-3aee-4aeb-8d18-5a636f1737e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>caf30f8d-6646-4245-a6c3-67008021c62a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>v_City</value>
         <variableId>26db0493-a3ef-4f5c-b441-12a070105bc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ee22f8e-b0a4-4505-87ac-084997e37a8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>caf30f8d-6646-4245-a6c3-67008021c62a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>v_Pin</value>
         <variableId>8414acef-5d4e-4911-b74e-f87deadd9f3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56bd000b-c4f4-4acd-9b59-e7339c2ef50e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aff9c8e-434e-4a6c-97fb-6cefeb46ec5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>307157d0-6687-41b8-968e-1db252a7a8bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/TC02_Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
