<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_PayersAccountNo</name>
   <tag></tag>
   <elementGuidId>6514fc6e-6871-4b7b-89cb-b9b45cf6c64b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>XPath:&#xd;
//input[@name='padd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//input[@name='padd']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'toadd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payersaccount</value>
      <webElementGuid>ab9efe18-260d-444f-854b-85df268130c1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
