name: Katalon Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Katalon Studio Test
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '10.3.1'
          projectPath: ${{ github.workspace }}
          args: >
            -noSplash
            -runMode=console
            -projectPath="${{ github.workspace }}"
            -retry=0
            -testSuitePath="Test Suites/Regression_Suite"
            -browserType="Chrome (headless)"
            -apiKey=${{ secrets.KATALON_API_KEY }}
